# vi docker-compose.yml
version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: dcl-mongo
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=dcladmin
            - MONGO_INITDB_ROOT_PASSWORD=dclp@ssw0rd
        image: mongo
